### User Register
POST http://localhost:3000/api/auth/register

{
    "name": "",
    "email": "alam_hash@gmail.com",
    "password": "passwordhash"
}

### User Login
POST http://localhost:3000/api/auth/login

{
    "email": "alam_hash@gmail.com",
    "password": "passwordhash"
}


### Delete Files
DELETE  http://localhost:3000/api/delete

{
    "folder": "XpJxkZDSUSMdYY_AcpJqN",
    "key": "4.png"
}

### Update Files
PATCH  http://localhost:3000/api/update

{
    "folder": "_IsS2mJB8RhrlJN8PWheb",
    "key": "Foto Terbaru.jpg"
}